version: '3.6'

services:
  mesh-demo:
      image: store/marklogicdb/marklogic-server:10.0-6-dev-centos
      container_name: mesh_demo
      domainname: .
      environment:
        - MARKLOGIC_INIT=true
        - MARKLOGIC_ADMIN_USERNAME=admin
        - MARKLOGIC_ADMIN_PASSWORD=admin
        - TZ=Europe/Prague
      ports:
        - 5432:5432
        - 7997-8013:7997-8013
      networks:
        - external_net
        - internal_net
      volumes:
        - 'marklogic:/var/opt/MarkLogic'
        - './data:/mnt/data'      
volumes:
  marklogic:
networks:
  external_net: {}
  internal_net:
    internal: true